#!/usr/bin/env node
'use strict';

/**
 * pulizia_residui_lavorazione — cancella i file CONSUMATI, e non sa cosa sia un
 * «residuo» guardando un nome.
 *
 * ══ LA REGOLA CHE COMANDA TUTTO, ed è negativa ══
 *
 *   UN FILE CHE ESISTE IN UN POSTO SOLO NON È UN RESIDUO: È L'UNICA COPIA.
 *
 * Il nome della skill dice «residui di lavorazione» e la parola pericolosa è
 * *residui*: un file che sembra vecchio è un residuo solo se nessuno lo usa, e
 * nessuno lo usa **non si sa guardando il nome**. Si sa guardando se esiste da
 * un'altra parte, e se non esiste, non lo si sa — quindi non si cancella.
 *
 * ══ TRE MODI, E IL PERICOLOSO È QUELLO CHE SI PUÒ SCHEDULARE ══
 *
 * L'umano vuole schedularla, quindi è un COMANDO e non un dialogo: nessuna
 * domanda, nessuna conferma per file. Esce con un codice e stampa un elenco.
 * *Una skill che chiede il permesso non è schedulabile: a un orario schedulato non
 * c'è nessuno a cui chiedere, e una richiesta che non trova nessuno o viene
 * saltata o blocca tutto — e in entrambi i casi non pulisce.*
 *
 *   --dry-run   (default)  non cancella NIENTE, scrive il manifesto, esce 0
 *   --applica              cancella SOLO ciò che il manifesto contiene
 *
 * `--applica` richiede **esattamente** il manifesto di una --dry-run precedente,
 * non più vecchio di MAX_AGE_GIORNI, e cancella solo le voci che il manifesto
 * contiene e che il disco CONFERMA essere ancora le stesse. Se il manifesto non
 * c'è, o non corrisponde più, non cancella niente e dice perché.
 *
 * *Un comando che cancella ciò che «ha trovato al momento» cancella qualcosa di
 * diverso da ciò che è stato approvato: e il divario fra le due cose è esattamente
 * dove si perde il lavoro.*
 *
 * ══ LA PRIMA ESECUZIONE NON CANCELLA NULLA, IN NESSUN MODO ══
 *
 * E non esiste un flag che lo permetta. *Uno strumento distruttivo che diventa
 * distruttivo al primo uso non è uno strumento che si è sbagliato a configurare:
 * è uno strumento che non è stato provato prima di fare il suo mestiere.*
 * La seconda esecuzione la preme l'umano, guardando il manifesto. Io posso
 * scrivere la riga che cancella; il diritto di premere quel tasto è suo.
 */

import { readdirSync, readFileSync, writeFileSync, statSync, existsSync, unlinkSync, mkdirSync } from 'node:fs';
import { join, relative, basename, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';

// ──Roots─────────────────────────────────────────────────────────────────────
const HIVE = 'F:/workspace/projects/ai-office/nemesi-office/hive';
const MUNDER = 'F:/workspace/projects/munder-difflin';
const ROOTS = [HIVE, MUNDER];

/** How old a --dry-run manifest may be before --applica refuses it. */
export const MAX_AGE_GIORNI = 7;

/**
 * Directories that hold DERIVED copies. A twin in one of these is a copy.
 *
 * `build` WAS in this list and the list was wrong, and it is worth writing down
 * why, because "it is called build" is exactly the reasoning that put it there.
 * In `munder-difflin`, `build/` holds **8 files tracked by git** — `icon.icns`,
 * `notarize.cjs`, `SIGNING.md` — and **0 untracked ones**. It is signing material
 * and packaging configuration somebody typed: source. The real build output is
 * `out/`, which has 0 tracked files and is named by `.gitignore` line 3.
 *
 * So the rule this list actually encodes is not "looks generated", it is
 * "somebody else's copy of the bytes". A directory that git TRACKS is by
 * definition content, whatever it is called. *A name is not a derivation, and a
 * list built from names is a list of guesses with a loop.*
 */
const COPY_DIRS = ['.opencode', '.claude', 'out', 'dist'];

// ══ LA LISTA DI «NON CANCELLARE MAI» — un contratto, scritto qui e non in un
// messaggio, perché un messaggio archiviato sparisce e un contratto no. ══

/** The floor's own memory. Deleting these is not tidying, it is amnesia. */
const MAI_PER_NOME = new Set([
  'tasks.json', 'tasks.archive.json', 'log.jsonl', 'registry.json', 'fleet.json',
  // mine, and declared as mine: an agent without its memory is a new agent
  'identity.md', 'memory.md',
  // the skill must never be a candidate for its own deletion
  'SKILL.md', 'pulizia.mjs'
]);

/** Suffixes whose whole purpose is to hold work that is not committed yet. */
const MAI_PER_SUFFISSO = ['.patch', '.diff'];

const MAI_PER_TASTO = [
  { per: /(^|\/)\.claim(\/|$)/, perche: 'a claim is a voice in progress: a live drainer owns it' },
  { per: /(^|\/)\.done(\/|$)/, perche: 'an archived message is the proof that somebody answered' },
  { per: /(^|\/)node_modules(\/|$)/, perche: 'regenerated by an install, not a residue' },
  { per: /(^|\/)\.git(\/|$)/, perche: 'it is the repository, not what is inside it' },
  { per: /\.receipt\.json$/, perche: 'a receipt is the record that something was spoken' },
  { per: /(^|\/)msg-[^/]*\.json$/, perche: 'a voice envelope' }
];

// ══ IL CONTRATTO DELLE USCITE ══
//
// Il nome di una directory non prova niente, e questa skill lo ha gia' imparato
// nel modo peggiore: `build/` era nella lista delle directory di copia perche' si
// chiama `build`, e conteneva 8 file tracciati che qualcuno aveva scritto. Quindi
// qui non si indovina: si DICHIARA, e ogni voce dichiarata viene verificata due
// volte all'avvio — la directory deve esistere come uscita reale e il comando che
// la rilancia deve esistere fra gli script di `package.json`.
//
// E' un contratto, come `MAI_PER_NOME`: sta in un file che non sparisce, non in un
// messaggio archiviato. Una voce sbagliata qui non cancella niente da sola — toglie
// solo la qualita' di «prova» a una cancellazione, quindi un contratto falso
// degrada verso «non si cancella», che e' la direzione in cui questa skill deve
// sbagliare.
//
// LA RIGA CHE MANCA, e che e' il punto 2 della card: «il file sembra generato» e'
// un GIUDIZIO. Il criterio verificabile e' che il file SPARISCE quando si pulisce
// l'artefatto e TORNA quando si rilancia. Percio' ogni voce porta la data della
// verifica empirica fatta a mano, e quella data e' la parte che la rende una prova
// e non un'asserzione: senza di lei questa tabella sarebbe una lista di buone
// intenzioni.

/** @type {{radice:string, dir:string, script:string, perche:string, verificatoIl:string}[]} */
export const USCITE_DICHIARATE = [
  {
    radice: MUNDER,
    dir: 'out',
    script: 'build',
    perche: 'electron-vite build && npm run copy:main-assets',
    verificatoIl: '2026-09-30 — rimossa la directory out/ e rilanciato `npm run build` (55,8 s): 115 file e 31 669 367 byte, cioe\' TUTTO quello che c\'era, piu\' 110 file di out/renderer che PRIMA non c\'erano. Il conto di «5 file» che avevo scritto prima era uno stato parziale, non la dimensione di out/ — *un numero letto al momento sbagliato e\' la forma piu\' economica di mentire, perche\' e\' un numero vero letto troppo tardi*'
  }
];

/**
 * The contract, minus every entry whose rebuild command does not exist.
 *
 * An entry whose `package.json` cannot be read is DROPPED, not assumed. "I could
 * not read the scripts" is not "there are no build scripts", and the difference is
 * the difference between a claim and a shrug — the same distinction `carteAperte()`
 * draws for the ledger, for the same reason.
 */
export function usciteValide(voci = USCITE_DICHIARATE) {
  const valide = [];
  for (const v of voci) {
    let pkg;
    try { pkg = JSON.parse(readFileSync(join(v.radice, 'package.json'), 'utf8')); }
    catch { continue; }
    const scripts = (pkg && pkg.scripts) || {};
    if (!Object.prototype.hasOwnProperty.call(scripts, v.script)) continue;
    if (!existsSync(join(v.radice, v.dir))) continue;
    valide.push(v);
  }
  return valide;
}

/**
 * Ask the REPOSITORY which of these paths it declares generated — in one call.
 *
 * Why `git check-ignore` and not a regex of mine: this skill already shipped the
 * bug where a hand-written path rule never matched the paths it was given (the
 * `.done` rule was written with `/`, the paths arrived with `\`), and the only
 * reason nothing was deleted was a second bug that happened to stop it. *A
 * protection list that does not match the paths it is given is not a protection
 * list, it is a comment.* The same applies to a proof: `.gitignore` semantics are
 * git's to answer, and asking git is cheaper and more honest than re-deriving them.
 *
 * `--stdin` because of the 100's other lesson: a proof that costs a spawn per file
 * is a stall with a justification attached. This is one spawn per root.
 *
 * NO `--no-index`, and that omission is load-bearing. Without it `check-ignore`
 * refuses to call a TRACKED file ignored — which is exactly the refusal we want: a
 * file git tracks is content, and the four `.opencode` trees in `hive/agents/<id>/`
 * are tracked, so this proof leaves them alone without anybody having to decide so.
 *
 * A root that is not a git work tree, or a git that is not installed, yields
 * `conosciuto: false` and an empty set: the answer becomes "no", never "yes".
 * An inconclusive scan is not a permission.
 */
function dichiaratiGeneratiDaGit(radice, assoluti) {
  const perRel = new Map();
  for (const p of assoluti) {
    const rel = relative(radice, p).replace(/\\/g, '/');
    if (!rel || rel.startsWith('../')) continue;
    perRel.set(rel, p);
  }
  if (!perRel.size) return { conosciuto: false, set: new Set() };
  const r = spawnSync('git', ['check-ignore', '--stdin'], {
    cwd: radice,
    input: [...perRel.keys()].join('\n') + '\n',
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
    windowsHide: true
  });
  if (r.error || r.status === 128) return { conosciuto: false, set: new Set() };
  const set = new Set();
  for (const riga of String(r.stdout || '').split('\n')) {
    // Trim first, then unquote. Git on Windows can end a line with CR, and a path
    // that ends in CR is not the path we asked about — an earlier measurement of
    // mine was misled by exactly that, and the symptom was a tool that reported
    // "nothing is ignored" for a directory git had just told me it ignores.
    const grezza = riga.replace(/\r$/, '');
    if (!grezza) continue;
    const rel = grezza.startsWith('"') && grezza.endsWith('"')
      ? grezza.slice(1, -1).replace(/\\(.)/g, '$1')
      : grezza;
    const abs = perRel.get(rel);
    if (abs) set.add(abs);
  }
  return { conosciuto: true, set };
}

/**
 * Proof `rigenerabile`: a command in this repository still rebuilds this file.
 *
 * This is the second of the two things that authorise, and the one the first real
 * run proved was missing: with only `gemello` the skill stops at the twins, and a
 * file with no twin is exactly what a build artefact usually is.
 *
 * Three facts, and the third is what keeps it a proof rather than a guess:
 *   1. the file is inside a directory this skill DECLARES as build output;
 *   2. the repository itself declares that path generated (`git check-ignore`);
 *   3. the command that rebuilds it exists, as a script, in that `package.json`
 *      — and the contract entry carries the date of a hand-run clean-and-rebuild.
 *
 * What it is NOT: a pattern. A git-ignored file that is not inside a declared
 * output directory — a `.log`, a `.env`, a `blog-preview` tree — is NOT proposed.
 * Otherwise this is `fuori uso` under a new name, one level up: "ignored" is not
 * "regenerable" exactly as "unreferenced" was not "derived", and the first real run
 * of this skill already paid for that mistake once.
 */
function rigenerabile(p, ctx) {
  if (!ctx.ignoreConosciuto) {
    return { prova: null, perche: 'NON SO se il repository lo dichiara generato: nessuna radice ha risposto, e una scansione non conclusa non e\' un permesso' };
  }
  const gruppo = ctx.uscite.find((u) => {
    const base = normalizza(u.radice + '/' + u.dir);
    return normalizza(p).startsWith(base + '/');
  });
  if (!gruppo) {
    return { prova: null, perche: 'nessun comando dichiarato produce la directory in cui sta' };
  }
  if (!ctx.ignorati.has(p)) {
    return { prova: null, perche: 'il repository NON lo dichiara generato, e un file che git traccia e\' contenuto' };
  }
  return {
    prova: 'rigenerabile',
    perche: 'lo produce `npm run ' + gruppo.script + '` (' + gruppo.perche + ') e il repository lo dichiara generato; verificato a mano il ' + gruppo.verificatoIl.split(' — ')[0],
    gruppo: gruppo.dir,
    comando: 'npm run ' + gruppo.script
  };
}

// ══ LE PROVE. Tre, e in tutte e tre la risposta è secca. ══

//
// «Una prova che richiede giudizio non è una prova: e se per decidere serve
// pensare, allora in un comando schedulato non nessuno pensa, e il comando
// indovina.» Quindi nessuna di queste chiede un'opinione: o il fatto c'è, o non c'è.

/** sha256 of a file, or null when it cannot be read. */
function sha256(p) {
  try { return createHash('sha256').update(readFileSync(p)).digest('hex'); } catch { return null; }
}

/**
 * One spelling for a path, used for every COMPARISON and never for touching disk.
 *
 * On this machine the same place arrives spelled three ways — a constant in this
 * file has forward slashes, `path.join` produces backslashes, and `.gitignore` uses
 * forward slashes — and a comparison that mixes two of them is a comparison that
 * does not match. That is not hypothetical: see the note at step 1b.
 */
function normalizza(p) {
  return String(p).replace(/\\/g, '/').replace(/\/+$/, '').toLowerCase();
}

/** Is this file inside a directory that holds derived copies? */
function inCopyDir(abs) {
  const parts = abs.split(/[\\/]/);
  return parts.some((seg) => COPY_DIRS.includes(seg));
}

function walk(root, out = [], prof = 0) {
  if (prof > 12) return out;
  let voci;
  try { voci = readdirSync(root, { withFileTypes: true }); } catch { return out; }
  for (const v of voci) {
    const p = join(root, v.name);
    // Never descend into a tree whose every file is protected anyway. Two reasons,
    // and the second is the one that bites: `.git` and `node_modules` hold tens of
    // thousands of files that can never be candidates, and walking them costs more
    // than the rest of the run put together. Skipping is not an approximation — the
    // protection list is a function of the PATH, and every path under those roots
    // matches the same pattern.
    if (v.isDirectory() && ALBERO_PROTETTO.some((r) => r.test(p.replace(/\\/g, '/')))) continue;
    if (v.isDirectory()) walk(p, out, prof + 1);
    else out.push(p);
  }
  return out;
}

const ALBERO_PROTETTO = [
  /(^|\/)\.git(\/|$)/,
  /(^|\/)node_modules(\/|$)/,
  /(^|\/)\.claim(\/|$)/,
  /(^|\/)\.done(\/|$)/
];

/**
 * Every path an OPEN card names, in whatever field it uses.
 * Read from the ledger, not guessed: a card that says it will touch a file has
 * an interest in that file, and the ledger is the only place that knows.
 */
function percorsiDichiarati(cardAperte) {
  const fuori = new Set();
  const percorso = /[A-Za-z]:[\\/][^\s"']+|(?:^|[\s"'`([])([A-Za-z0-9_.-]+(?:[\\/][A-Za-z0-9_.-]+)+)/g;
  for (const c of cardAperte) {
    const testo = JSON.stringify(c);
    let m;
    while ((m = percorso.exec(testo)) !== null) {
      const grezzo = (m[0] || '').replace(/^[\s"'`([]/, '').replace(/[.,;:]+$/, '');
      if (!grezzo || grezzo.length < 6) continue;
      fuori.add(grezzo.replace(/[\\/]/g, '/').toLowerCase());
      fuori.add(basename(grezzo).toLowerCase());
    }
  }
  return fuori;
}

/**
 * The open cards, or a refusal.
 *
 * `chain.cjs` writes `tasks.json` with a plain `writeFileSync` **in place** — not a
 * temp file and a rename — so a reader that arrives during a write sees a
 * TRUNCATED file. That is not theoretical: reading the floor's own ledger tonight
 * returned "Unexpected end of JSON input", and five seconds later the same file was
 * valid and had grown by 175 bytes.
 *
 * Which is why the catch here does NOT return an empty list. An empty list is the
 * answer that makes this skill least careful — "no open card declares anything" is
 * exactly the claim that `fuori uso` is built on, and it would be a claim made from
 * a file we failed to read. *A tool that cannot see the rules must assume the rules
 * forbid it, because the alternative is a tool that assumes nobody set any.*
 */
function carteAperte() {
  try {
    const t = JSON.parse(readFileSync(join(HIVE, 'tasks.json'), 'utf8'));
    const a = t.tasks || t;
    if (!Array.isArray(a)) return { ok: false, carte: [], motivo: 'tasks.json non contiene un elenco di card' };
    return { ok: true, carte: a.filter((c) => c && c.status !== 'done' && c.status !== 'cancelled'), motivo: '' };
  } catch (e) {
    return { ok: false, carte: [], motivo: 'NON RIESCO A LEGGERE tasks.json (' + e.message + '): finche\' non lo leggo non posso sapere che cosa dichiarano le card aperte, e cio\' vale come «non dichiarato da nessuna», che e\' la risposta che rende questo strumento MENO cauto' };
  }
}

/**
 * Every basename any tool or source file mentions, read ONCE.
 *
 * This is an INDEX, and it is an index because the first version of this function
 * grepped the tools and the source again for every single candidate — and on the
 * real floor that is 53 750 files times the size of the source tree. The first
 * dry run did not finish in thirty minutes. *A proof that costs a whole scan per
 * file is not a proof, it is a stall with a justification attached.*
 */
function indiceNomiLetti() {
  const nomi = new Set();
  for (const radice of [join(HIVE, 'tools'), join(MUNDER, 'src')]) {
    for (const f of walk(radice)) {
      if (!/\.(cjs|mjs|js|ts|tsx|json|md)$/.test(f)) continue;
      let st; try { st = statSync(f); } catch { continue; }
      if (st.size > 2 * 1024 * 1024) continue; // a 2 MB "tool" is not a tool
      let t; try { t = readFileSync(f, 'utf8'); } catch { continue; }
      for (const m of t.matchAll(/[A-Za-z0-9_.-]+\.(?:json|cjs|mjs|js|ts|tsx|md|jsonl|patch)/g)) {
        nomi.add(m[0].toLowerCase());
      }
    }
  }
  return nomi;
}

/**
 * Proof `fuori uso`: no open card names it, and no tool or source file mentions
 * it by name. A grep is a boolean, and a boolean is something a scheduled
 * command can hold — a judgement would need somebody thinking, and at an hour
 * nobody scheduled is thinking.
 */
function fuoriUso(p, ctx) {
  const nome = basename(p).toLowerCase();
  if (ctx.dichiarati.has(nome) || ctx.dichiarati.has(p.replace(/\\/g, '/').toLowerCase())) {
    return { ok: false, perche: 'una card aperta lo dichiara' };
  }
  if (ctx.nomiLetti.has(nome)) {
    return { ok: false, perche: 'e\' nominato da uno strumento o da un sorgente, quindi qualcosa lo legge' };
  }
  return { ok: true, perche: 'nessuna card aperta lo dichiara e nessuno strumento o sorgente lo nomina' };
}

/**
 * Build the plan. Nothing is deleted here and nothing can be: this function only
 * ever writes one file, the manifest, and that is by design.
 */
export function costruisciPiano(opts = {}) {
  const roots = opts.roots || ROOTS;
  const carte = opts.carte === undefined ? carteAperte() : opts.carte;
  const ctx = {
    carteOk: carte.ok,
    motivoLedger: carte.motivo,
    dichiarati: opts.dichiarati || percorsiDichiarati(carte.carte),
    nomiLetti: opts.nomiLetti || indiceNomiLetti(),
    // The declared outputs, already checked against the package.json that has to
    // still exist. An entry that fails the check is not in here, so a stale
    // contract claims nothing rather than claiming something false.
    uscite: opts.usciteValide || usciteValide(opts.uscite),
    ignorati: new Set(),
    ignoreConosciuto: false,
    hashPerSha: new Map(),     // sha -> [paths]
    file: [],
    protetti: []
  };

  // 1) collect, and separate the untouchable from the candidates
  for (const radice of roots) {
    for (const p of walk(radice)) {
      let st; try { st = statSync(p); } catch { continue; }
      if (!st.isFile()) continue;
      const motivo = percheProtetto(p, ctx);
      if (motivo) { ctx.protetti.push({ path: p, perche: motivo }); continue; }
      ctx.file.push({ path: p, bytes: st.size, inCopia: inCopyDir(p) });
    }
  }

  // 1b) ask the repositories, once per root, which of the candidates they declare
  //     generated. This is the input the `rigenerabile` proof is made of, so it is
  //     gathered for every candidate and not per candidate: one spawn per root.
  //
  //     BOTH SIDES NORMALISED, and the reason is the bug this replaced. `ROOTS` holds
  //     `MUNDER` with FORWARD slashes; `walk()` hands back paths with BACKSLASHES.
  //     So `p.startsWith(radice + '\\')` matched NOTHING on the real floor, no
  //     candidate was ever asked about, and the whole proof reported zero — silently,
  //     with the unit tests green, because a temp dir and its own children agree on
  //     their separators and the two constants do not.
  //     *È lo stesso difetto della 100, ripetuto un livello più su: una regola che
  //     non aggancia i percorsi che riceve non è una regola, è un commento — e un
  //     test costruito su una forma sola non la può vedere.*
  for (const radice of roots) {
    const base = normalizza(radice);
    const qui = ctx.file.filter((f) => normalizza(f.path).startsWith(base + '/'));
    if (!qui.length) continue;
    const r = dichiaratiGeneratiDaGit(radice, qui.map((f) => f.path));
    if (r.conosciuto) ctx.ignoreConosciuto = true;
    for (const p of r.set) ctx.ignorati.add(p);
  }

  // 2) hash the candidates. This is the expensive step and it is honest about it:
  //    the twin proof is content-based, so there is no cheaper version of it.
  for (const f of ctx.file) {
    const h = sha256(f.path);
    if (!h) continue;
    f.sha = h;
    if (!ctx.hashPerSha.has(h)) ctx.hashPerSha.set(h, []);
    ctx.hashPerSha.get(h).push(f.path);
  }

  // 3) prove each candidate. A file with no proof is NOT a residue, full stop.
  //
  //    AND for a set of identical files, ONE OF THEM IS THE KEEPER. This is the
  //    card's own title — «senza mai cancellare l'unica copia» — and with three
  //    identical trees a naive twin proof would happily delete all three, because
  //    at the moment of each decision the other two still existed. The rule has to
  //    be about the SET, not about the pair: *two witnesses who each think the
  //    other is the backup is how a whole set disappears.*
  const keeperPerSha = new Map();
  for (const [h, paths] of ctx.hashPerSha) {
    if (paths.length < 2) continue;
    // prefer a source location over a copy directory, then the shortest path
    const ordinati = [...paths].sort((a, b) => {
      const ca = inCopyDir(a) ? 1 : 0, cb = inCopyDir(b) ? 1 : 0;
      if (ca !== cb) return ca - cb;
      return a.length - b.length;
    });
    keeperPerSha.set(h, ordinati[0]);
  }

  const proposti = [];
  for (const f of ctx.file) {
    const prova = dimostra(f, ctx, keeperPerSha);
    // The filter is on `prova.prova`, NOT on the object. Returning an object whose
    // `prova` is null still returns a truthy object, and the first real run
    // cheerfully listed 4 219 files with `[null]` next to them — a plan that says
    // "propose everything, and here is no reason". *A guard on the wrong field is a
    // guard that is not there.*
    if (prova && prova.prova) {
      proposti.push({
        ...f,
        prova: prova.prova,
        perche: prova.perche,
        // `gruppo` and `comando` travel with the entry, because the unit that is
        // safe to remove for a build output is the DIRECTORY, not the file: the
        // directory is atomic and its children are not. A manifest that lists 3 000
        // files without saying they are one artifact tree has described the wrong
        // unit, and the reader has to reassemble it by hand.
        gruppo: prova.gruppo || null,
        comando: prova.comando || null
      });
    }
  }
  proposti.sort((a, b) => b.bytes - a.bytes);

  // The regenerable entries, GROUPED, so the manifest names the thing a person can
  // actually decide about: «this whole tree, and here is the command that puts it
  // back». Per-file proposals hide the fact that the 3 000 are one decision.
  const perGruppo = new Map();
  for (const p of proposti) {
    if (p.prova !== 'rigenerabile' || !p.gruppo) continue;
    const k = p.gruppo;
    if (!perGruppo.has(k)) perGruppo.set(k, { gruppo: k, comando: p.comando, file: 0, bytes: 0 });
    const g = perGruppo.get(k);
    g.file++; g.bytes += p.bytes;
  }
  const rigenerabili = [...perGruppo.values()].sort((a, b) => b.bytes - a.bytes);

  const byteTrovati = ctx.file.reduce((s, f) => s + f.bytes, 0);
  const byteProposti = proposti.reduce((s, f) => s + f.bytes, 0);
  const byteRigenerabili = rigenerabili.reduce((s, g) => s + g.bytes, 0);
  return {
    generatoIl: new Date().toISOString(),
    radici: roots,
    contatori: {
      fileTrovati: ctx.file.length,
      fileProtetti: ctx.protetti.length,
      fileProposti: proposti.length,
      filePropostiPerGemello: proposti.filter((p) => p.prova === 'gemello').length,
      filePropostiPerRigenerabile: proposti.filter((p) => p.prova === 'rigenerabile').length,
      // The number the card is really about: without a second authorising proof the
      // skill stops at the twins, and this is how many bytes it could not explain.
      byteProposti,
      byteRigenerabili,
      byteTrovati,
      byteCancellati: 0
    },
    proposte: proposti,
    rigenerabili,
    // The protected list goes in the manifest too: the next reader must be able
    // to see WHAT WAS SPARED, not only what was offered. A manifest that lists
    // only the victims is a manifest that cannot be argued with.
    protetti: ctx.protetti.map((p) => ({ path: p.path, perche: p.perche })),
    regola: 'UN FILE CHE ESISTE IN UN POSTO SOLO NON È UN RESIDUO: È L\'UNICA COPIA.',
    regolaProva: 'ALLA PROVA PUÒ AUTORIZZARE; IL GIUDIZIO VA DALL\'UMANO.'
  };
}

function percheProtetto(p, ctx) {
  const nome = basename(p);
  // EVERY pattern above is written with forward slashes, and on this machine the
  // paths arrive with backslashes. The first real run proved what that costs: the
  // `.done` rule silently never matched, 500-odd archived messages were walked and
  // hashed as if they were candidates, and the only reason nothing was deleted was
  // that a second, unrelated bug happened to stop it. *A protection list that does
  // not match the paths it is given is not a protection list, it is a comment.*
  const norm = p.replace(/\\/g, '/');
  if (MAI_PER_NOME.has(nome)) return 'memoria del pavimento: ' + nome;
  if (MAI_PER_SUFFISSO.some((s) => nome.endsWith(s))) return 'lavoro non committato: ' + nome;
  for (const t of MAI_PER_TASTO) if (t.per.test(norm)) return t.perche;
  if (norm.includes('/resources/skills/pulizia_residui_lavorazione/')) {
    return 'la skill non e\' un proprio residuo: se si include, la prossima esecuzione cerca di cancellare se\' stessa';
  }
  if (ctx.dichiarati.has(nome)) return 'una card aperta lo dichiara';
  if (ctx.carteOk === false) return ctx.motivoLedger;
  return null;
}

/** Exactly one of the three proofs, or nothing. */
function dimostra(f, ctx, keeperPerSha) {
  // GEMELLO — the same content exists elsewhere, at least one copy is in a copy
  // directory, AND this file is not the one the set keeps. A pure fact about
  // bytes, and the only proof that needs no opinion at all.
  if (f.sha) {
    const gemelli = (ctx.hashPerSha.get(f.sha) || []).filter((q) => q !== f.path);
    if (gemelli.length) {
      if (!inCopyDir(f.path) && !gemelli.some(inCopyDir)) {
        return { prova: null, perche: 'contenuto identico ma NESSUNA delle due copie e\' in una directory di copia: due file con lo stesso testo non sono una copia, e trattarli come tale cancella un originale' };
      }
      const keeper = keeperPerSha.get(f.sha);
      if (keeper === f.path) {
        return { prova: null, perche: 'e\' LA COPIA CHE IL GRUPPO TENNE: ' + gemelli.length + ' file identici esistono, e questo e\' quello che resta se gli altri se ne vanno. Un set senza un custode e\' un set che sparisce' };
      }
      return {
        prova: 'gemello',
        perche: 'contenuto identico (sha ' + f.sha.slice(0, 12) + '…) in ' + gemelli.length
          + ' altro/i file, almeno uno in una directory di copia; resta ' + relative(ROOTS[0], keeper)
      };
    }
  }
  // FUORI USO — this was my first implementation and it was a TRAP, and the trap
  // is worth writing down because it is easy to fall into again.
  //
  // Read literally, "no open card declares it, no tool reads it, no config names
  // it" is true of almost EVERY file in a repository — including the source code.
  // The first real dry run proved it: it proposed 4 218 files out of 4 218
  // found, among them `docs/media/hero.mp4` and a skill's illustrations, all
  // labelled «fuori uso». *Absence of a reference is not derivation: it is the
  // normal state of every file, and a proof that is true of everything proves
  // nothing.*
  //
  // So `fuori uso` does NOT authorise a deletion. It is recorded as a NOTE, next
  // to the file, and the file is not proposed. The only two things that authorise
  // are the two the card's governing rule actually names: the same content exists
  // elsewhere, or a command that still rebuilds it. *The card lists three proofs
  // and then says only derived files may be deleted; those two sentences do not
  // agree, and the one that says «derivato» wins, because the other one would
  // delete the repository.*
  // RIGENERABILE — the second of the two authorising proofs, and the one the first
  // real run proved was missing. Its verdict is the opposite shape of `fuori uso`:
  // `fuori uso` was true of everything and therefore worthless, and this one is
  // narrow on purpose. It says YES only where a declared command rebuilds the file
  // AND the repository itself says the path is generated, and it says NO — with the
  // reason — everywhere else, which is what makes it a proof that can fail.
  const rig = rigenerabile(f.path, ctx);
  if (rig.prova) return rig;

  const nota = fuoriUso(f.path, ctx);
  return {
    prova: null,
    perche: 'fuori uso NON prova niente: ' + nota.perche
      + (rig.perche ? '  [rigenerabile: ' + rig.perche + ']' : '')
  };
}

function percorsoManifesto() {
  const d = join(HIVE, 'pulizia');
  mkdirSync(d, { recursive: true });
  const giorno = new Date().toISOString().slice(0, 10);
  return join(d, `pulizia-${giorno}.json`);
}

function stampa(piano, cancellati) {
  const c = piano.contatori;
  console.log('pulizia_residui_lavorazione — ' + new Date().toISOString());
  console.log('  file trovati   : ' + c.fileTrovati);
  console.log('  file protetti  : ' + c.fileProtetti);
  console.log('  file proposti  : ' + c.fileProposti);
  if (c.filePropostiPerGemello !== undefined) {
    console.log('      per gemello       : ' + c.filePropostiPerGemello);
    console.log('      per rigenerabile  : ' + c.filePropostiPerRigenerabile);
  }
  console.log('  byte trovati   : ' + c.byteTrovati);
  console.log('  byte proposti  : ' + c.byteProposti);
  console.log('  byte cancellati: ' + (cancellati === undefined ? 0 : cancellati));
  if (piano.rigenerabili && piano.rigenerabili.length) {
    console.log('\n  rigenerabili, per directory (l\'unita\' che si decide e\' l\'albero, non il file):');
    for (const g of piano.rigenerabili) {
      console.log('    ' + g.gruppo + '/  ' + g.file + ' file  ' + g.bytes + ' B  ⟵ ' + g.comando);
    }
  }
  if (piano.proposte.length) {
    console.log('\n  proposte (percorso | byte | prova | perche):');
    for (const p of piano.proposte.slice(0, 40)) {
      console.log('    ' + p.path);
      console.log('        ' + p.bytes + ' B  [' + p.prova + ']  ' + p.perche);
    }
    if (piano.proposte.length > 40) console.log('    ... e altre ' + (piano.proposte.length - 40));
  }
  console.log('\n  regola: ' + piano.regola);
  if (piano.regolaProva) console.log('  regola: ' + piano.regolaProva);
}

// ── main ────────────────────────────────────────────────────────────────────
function main(argv) {
  const applica = argv.includes('--applica');
  const iMan = argv.indexOf('--manifest');
  const piano = costruisciPiano({});

  if (!applica) {
    const p = percorsoManifesto();
    writeFileSync(p, JSON.stringify(piano, null, 2), 'utf8');
    stampa(piano);
    console.log('\n  manifesto: ' + p);
    console.log('  NESSUN FILE CANCELLATO. La seconda esecuzione la preme l\'umano, guardando questo elenco.');
    return 0;
  }

  // ── --applica: the manifest decides, and only the manifest ──
  const da = iMan >= 0 ? argv[iMan + 1] : percorsoManifesto();
  if (!da || !existsSync(da)) {
    console.error('NON CANCELLO NIENTE: nessun manifesto in "' + (da || '(manca --manifest)') + '".');
    console.error('  --applica cancella solo ciò che una --dry-run ha già scritto e che l\'umano ha guardato.');
    return 3;
  }
  let m;
  try { m = JSON.parse(readFileSync(da, 'utf8')); } catch {
    console.error('NON CANCELLO NIENTE: il manifesto non è JSON leggibile (' + da + ').');
    return 4;
  }
  const eta = (Date.now() - Date.parse(m.generatoIl)) / 86400000;
  if (!(eta <= MAX_AGE_GIORNI)) {
    console.error('NON CANCELLO NIENTE: il manifesto ha ' + eta.toFixed(1) + ' giorni, e il massimo è ' + MAX_AGE_GIORNI + '.');
    console.error('  Un piano vecchio descrive un disco che nel frattempo è cambiato: rifai la --dry-run.');
    return 5;
  }
  if (!Array.isArray(m.proposte) || !m.proposte.length) {
    console.error('NON CANCELLO NIENTE: il manifesto non propone nulla. E\' il caso normale su un pavimento pulito.');
    return 0;
  }

  let cancellati = 0, saltati = 0, byteCancellati = 0;
  const registro = [];
  // A `rigenerabile` proposal rests on the repository declaring the path generated.
  // Between the plan and the press that can change — somebody un-ignores a path,
  // or `git check-ignore` starts answering differently — and that is exactly the
  // window in which the reason for the proposal disappears while the entry stays.
  // So the reason is re-checked, in one batch, and anything that no longer holds is
  // skipped rather than deleted.
  const rigDaRivedere = m.proposte.filter((p) => p.prova === 'rigenerabile' && p.sha).map((p) => p.path);
  const ancoraIgnorati = new Set();
  for (const radice of m.radici || []) {
    const base = normalizza(radice);
    const qui = rigDaRivedere.filter((p) => normalizza(p).startsWith(base + '/'));
    if (!qui.length) continue;
    const r = dichiaratiGeneratiDaGit(radice, qui);
    for (const p of r.set) ancoraIgnorati.add(p);
  }
  for (const p of m.proposte) {
    // Re-verify BOTH that it is still what the manifest said, and that it is still
    // protected-free. A path can have become something else between the plan and
    // the press, and that is the window where work is lost.
    let st; try { st = statSync(p.path); } catch { saltati++; registro.push({ path: p.path, esito: 'non esiste piu\'' }); continue; }
    const h = sha256(p.path);
    if (p.sha && h !== p.sha) { saltati++; registro.push({ path: p.path, esito: 'contenuto cambiato: non e\' piu\' quello approvato' }); continue; }
    if (p.prova === 'rigenerabile' && !ancoraIgnorati.has(p.path)) {
      saltati++;
      registro.push({ path: p.path, esito: 'il repository non lo dichiara piu\' generato: la prova non regge piu\'' });
      continue;
    }
    if (percheProtetto(p.path, { dichiarati: new Set() })) { saltati++; registro.push({ path: p.path, esito: 'ora e\' protetto' }); continue; }
    try { unlinkSync(p.path); cancellati++; byteCancellati += st.size; registro.push({ path: p.path, esito: 'cancellato', bytes: st.size }); }
    catch (e) { saltati++; registro.push({ path: p.path, esito: 'cancellamento fallito: ' + e.code }); }
  }
  m.contatori.byteCancellati = byteCancellati;
  m.esito = { cancellati, saltati, byteCancellati, eseguitoIl: new Date().toISOString() };
  writeFileSync(da, JSON.stringify(m, null, 2), 'utf8');
  stampa(m, byteCancellati);
  console.log('\n  cancellati: ' + cancellati + '  saltati: ' + saltati);
  for (const r of registro.slice(0, 40)) console.log('    ' + r.esito + '  ' + r.path);
  if (saltati) console.log('\n  I SALTATI NON SONO UN ERRORE: sono file che nel frattempo non erano piu\' quelli approvati,');
  console.log('  e cancellarli avrebbe significato cancellare qualcosa di diverso da cio che e\' stato approvato.');
  return 0;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  process.exit(main(process.argv.slice(2)));
}
