#!/usr/bin/env node
'use strict';

/**
 * pulizia_residui_lavorazione — cancella i file CONSUMATI, e non sa cosa sia un
 * «residuo» guardando un nome.
 *
 * ══ LA REGOLA CHE COMANDA TUTTO, ed è negativa ══
 *
 *   UN FILE CHE ESISTE IN UN POSTO SOLO NON È UN RESIDUO: È L'UNICA COPIA.
 *
 * Il nome della skill dice «residui di lavorazione» e la parola pericolosa è
 * *residui*: un file che sembra vecchio è un residuo solo se nessuno lo usa, e
 * nessuno lo usa **non si sa guardando il nome**. Si sa guardando se esiste da
 * un'altra parte, e se non esiste, non lo si sa — quindi non si cancella.
 *
 * ══ TRE MODI, E IL PERICOLOSO È QUELLO CHE SI PUÒ SCHEDULARE ══
 *
 * L'umano vuole schedularla, quindi è un COMANDO e non un dialogo: nessuna
 * domanda, nessuna conferma per file. Esce con un codice e stampa un elenco.
 * *Una skill che chiede il permesso non è schedulabile: a un orario schedulato non
 * c'è nessuno a cui chiedere, e una richiesta che non trova nessuno o viene
 * saltata o blocca tutto — e in entrambi i casi non pulisce.*
 *
 *   --dry-run   (default)  non cancella NIENTE, scrive il manifesto, esce 0
 *   --applica              cancella SOLO ciò che il manifesto contiene
 *
 * `--applica` richiede **esattamente** il manifesto di una --dry-run precedente,
 * non più vecchio di MAX_AGE_GIORNI, e cancella solo le voci che il manifesto
 * contiene e che il disco CONFERMA essere ancora le stesse. Se il manifesto non
 * c'è, o non corrisponde più, non cancella niente e dice perché.
 *
 * *Un comando che cancella ciò che «ha trovato al momento» cancella qualcosa di
 * diverso da ciò che è stato approvato: e il divario fra le due cose è esattamente
 * dove si perde il lavoro.*
 *
 * ══ LA PRIMA ESECUZIONE NON CANCELLA NULLA, IN NESSUN MODO ══
 *
 * E non esiste un flag che lo permetta. *Uno strumento distruttivo che diventa
 * distruttivo al primo uso non è uno strumento che si è sbagliato a configurare:
 * è uno strumento che non è stato provato prima di fare il suo mestiere.*
 * La seconda esecuzione la preme l'umano, guardando il manifesto. Io posso
 * scrivere la riga che cancella; il diritto di premere quel tasto è suo.
 */

import { readdirSync, readFileSync, writeFileSync, statSync, existsSync, unlinkSync, mkdirSync } from 'node:fs';
import { join, relative, basename, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

// ──Roots─────────────────────────────────────────────────────────────────────
const HIVE = 'F:/workspace/projects/ai-office/nemesi-office/hive';
const MUNDER = 'F:/workspace/projects/munder-difflin';
const ROOTS = [HIVE, MUNDER];

/** How old a --dry-run manifest may be before --applica refuses it. */
export const MAX_AGE_GIORNI = 7;

/** Directories that hold DERIVED copies. A twin in one of these is a copy. */
const COPY_DIRS = ['.opencode', '.claude', 'out', 'dist', 'build'];

// ══ LA LISTA DI «NON CANCELLARE MAI» — un contratto, scritto qui e non in un
// messaggio, perché un messaggio archiviato sparisce e un contratto no. ══

/** The floor's own memory. Deleting these is not tidying, it is amnesia. */
const MAI_PER_NOME = new Set([
  'tasks.json', 'tasks.archive.json', 'log.jsonl', 'registry.json', 'fleet.json',
  // mine, and declared as mine: an agent without its memory is a new agent
  'identity.md', 'memory.md',
  // the skill must never be a candidate for its own deletion
  'SKILL.md', 'pulizia.mjs'
]);

/** Suffixes whose whole purpose is to hold work that is not committed yet. */
const MAI_PER_SUFFISSO = ['.patch', '.diff'];

const MAI_PER_TASTO = [
  { per: /(^|\/)\.claim(\/|$)/, perche: 'a claim is a voice in progress: a live drainer owns it' },
  { per: /(^|\/)\.done(\/|$)/, perche: 'an archived message is the proof that somebody answered' },
  { per: /(^|\/)node_modules(\/|$)/, perche: 'regenerated by an install, not a residue' },
  { per: /(^|\/)\.git(\/|$)/, perche: 'it is the repository, not what is inside it' },
  { per: /\.receipt\.json$/, perche: 'a receipt is the record that something was spoken' },
  { per: /(^|\/)msg-[^/]*\.json$/, perche: 'a voice envelope' }
];

// ══ LE PROVE. Tre, e in tutte e tre la risposta è secca. ══
//
// «Una prova che richiede giudizio non è una prova: e se per decidere serve
// pensare, allora in un comando schedulato non nessuno pensa, e il comando
// indovina.» Quindi nessuna di queste chiede un'opinione: o il fatto c'è, o non c'è.

/** sha256 of a file, or null when it cannot be read. */
function sha256(p) {
  try { return createHash('sha256').update(readFileSync(p)).digest('hex'); } catch { return null; }
}

/** Is this file inside a directory that holds derived copies? */
function inCopyDir(abs) {
  const parts = abs.split(/[\\/]/);
  return parts.some((seg) => COPY_DIRS.includes(seg));
}

function walk(root, out = [], prof = 0) {
  if (prof > 12) return out;
  let voci;
  try { voci = readdirSync(root, { withFileTypes: true }); } catch { return out; }
  for (const v of voci) {
    const p = join(root, v.name);
    // Never descend into a tree whose every file is protected anyway. Two reasons,
    // and the second is the one that bites: `.git` and `node_modules` hold tens of
    // thousands of files that can never be candidates, and walking them costs more
    // than the rest of the run put together. Skipping is not an approximation — the
    // protection list is a function of the PATH, and every path under those roots
    // matches the same pattern.
    if (v.isDirectory() && ALBERO_PROTETTO.some((r) => r.test(p.replace(/\\/g, '/')))) continue;
    if (v.isDirectory()) walk(p, out, prof + 1);
    else out.push(p);
  }
  return out;
}

const ALBERO_PROTETTO = [
  /(^|\/)\.git(\/|$)/,
  /(^|\/)node_modules(\/|$)/,
  /(^|\/)\.claim(\/|$)/,
  /(^|\/)\.done(\/|$)/
];

/**
 * Every path an OPEN card names, in whatever field it uses.
 * Read from the ledger, not guessed: a card that says it will touch a file has
 * an interest in that file, and the ledger is the only place that knows.
 */
function percorsiDichiarati(cardAperte) {
  const fuori = new Set();
  const percorso = /[A-Za-z]:[\\/][^\s"']+|(?:^|[\s"'`([])([A-Za-z0-9_.-]+(?:[\\/][A-Za-z0-9_.-]+)+)/g;
  for (const c of cardAperte) {
    const testo = JSON.stringify(c);
    let m;
    while ((m = percorso.exec(testo)) !== null) {
      const grezzo = (m[0] || '').replace(/^[\s"'`([]/, '').replace(/[.,;:]+$/, '');
      if (!grezzo || grezzo.length < 6) continue;
      fuori.add(grezzo.replace(/[\\/]/g, '/').toLowerCase());
      fuori.add(basename(grezzo).toLowerCase());
    }
  }
  return fuori;
}

/**
 * The open cards, or a refusal.
 *
 * `chain.cjs` writes `tasks.json` with a plain `writeFileSync` **in place** — not a
 * temp file and a rename — so a reader that arrives during a write sees a
 * TRUNCATED file. That is not theoretical: reading the floor's own ledger tonight
 * returned "Unexpected end of JSON input", and five seconds later the same file was
 * valid and had grown by 175 bytes.
 *
 * Which is why the catch here does NOT return an empty list. An empty list is the
 * answer that makes this skill least careful — "no open card declares anything" is
 * exactly the claim that `fuori uso` is built on, and it would be a claim made from
 * a file we failed to read. *A tool that cannot see the rules must assume the rules
 * forbid it, because the alternative is a tool that assumes nobody set any.*
 */
function carteAperte() {
  try {
    const t = JSON.parse(readFileSync(join(HIVE, 'tasks.json'), 'utf8'));
    const a = t.tasks || t;
    if (!Array.isArray(a)) return { ok: false, carte: [], motivo: 'tasks.json non contiene un elenco di card' };
    return { ok: true, carte: a.filter((c) => c && c.status !== 'done' && c.status !== 'cancelled'), motivo: '' };
  } catch (e) {
    return { ok: false, carte: [], motivo: 'NON RIESCO A LEGGERE tasks.json (' + e.message + '): finche\' non lo leggo non posso sapere che cosa dichiarano le card aperte, e cio\' vale come «non dichiarato da nessuna», che e\' la risposta che rende questo strumento MENO cauto' };
  }
}

/**
 * Every basename any tool or source file mentions, read ONCE.
 *
 * This is an INDEX, and it is an index because the first version of this function
 * grepped the tools and the source again for every single candidate — and on the
 * real floor that is 53 750 files times the size of the source tree. The first
 * dry run did not finish in thirty minutes. *A proof that costs a whole scan per
 * file is not a proof, it is a stall with a justification attached.*
 */
function indiceNomiLetti() {
  const nomi = new Set();
  for (const radice of [join(HIVE, 'tools'), join(MUNDER, 'src')]) {
    for (const f of walk(radice)) {
      if (!/\.(cjs|mjs|js|ts|tsx|json|md)$/.test(f)) continue;
      let st; try { st = statSync(f); } catch { continue; }
      if (st.size > 2 * 1024 * 1024) continue; // a 2 MB "tool" is not a tool
      let t; try { t = readFileSync(f, 'utf8'); } catch { continue; }
      for (const m of t.matchAll(/[A-Za-z0-9_.-]+\.(?:json|cjs|mjs|js|ts|tsx|md|jsonl|patch)/g)) {
        nomi.add(m[0].toLowerCase());
      }
    }
  }
  return nomi;
}

/**
 * Proof `fuori uso`: no open card names it, and no tool or source file mentions
 * it by name. A grep is a boolean, and a boolean is something a scheduled
 * command can hold — a judgement would need somebody thinking, and at an hour
 * nobody scheduled is thinking.
 */
function fuoriUso(p, ctx) {
  const nome = basename(p).toLowerCase();
  if (ctx.dichiarati.has(nome) || ctx.dichiarati.has(p.replace(/\\/g, '/').toLowerCase())) {
    return { ok: false, perche: 'una card aperta lo dichiara' };
  }
  if (ctx.nomiLetti.has(nome)) {
    return { ok: false, perche: 'e\' nominato da uno strumento o da un sorgente, quindi qualcosa lo legge' };
  }
  return { ok: true, perche: 'nessuna card aperta lo dichiara e nessuno strumento o sorgente lo nomina' };
}

/**
 * Build the plan. Nothing is deleted here and nothing can be: this function only
 * ever writes one file, the manifest, and that is by design.
 */
export function costruisciPiano(opts = {}) {
  const roots = opts.roots || ROOTS;
  const carte = opts.carte === undefined ? carteAperte() : opts.carte;
  const ctx = {
    carteOk: carte.ok,
    motivoLedger: carte.motivo,
    dichiarati: opts.dichiarati || percorsiDichiarati(carte.carte),
    nomiLetti: opts.nomiLetti || indiceNomiLetti(),
    hashPerSha: new Map(),     // sha -> [paths]
    file: [],
    protetti: []
  };

  // 1) collect, and separate the untouchable from the candidates
  for (const radice of roots) {
    for (const p of walk(radice)) {
      let st; try { st = statSync(p); } catch { continue; }
      if (!st.isFile()) continue;
      const motivo = percheProtetto(p, ctx);
      if (motivo) { ctx.protetti.push({ path: p, perche: motivo }); continue; }
      ctx.file.push({ path: p, bytes: st.size, inCopia: inCopyDir(p) });
    }
  }

  // 2) hash the candidates. This is the expensive step and it is honest about it:
  //    the twin proof is content-based, so there is no cheaper version of it.
  for (const f of ctx.file) {
    const h = sha256(f.path);
    if (!h) continue;
    f.sha = h;
    if (!ctx.hashPerSha.has(h)) ctx.hashPerSha.set(h, []);
    ctx.hashPerSha.get(h).push(f.path);
  }

  // 3) prove each candidate. A file with no proof is NOT a residue, full stop.
  //
  //    AND for a set of identical files, ONE OF THEM IS THE KEEPER. This is the
  //    card's own title — «senza mai cancellare l'unica copia» — and with three
  //    identical trees a naive twin proof would happily delete all three, because
  //    at the moment of each decision the other two still existed. The rule has to
  //    be about the SET, not about the pair: *two witnesses who each think the
  //    other is the backup is how a whole set disappears.*
  const keeperPerSha = new Map();
  for (const [h, paths] of ctx.hashPerSha) {
    if (paths.length < 2) continue;
    // prefer a source location over a copy directory, then the shortest path
    const ordinati = [...paths].sort((a, b) => {
      const ca = inCopyDir(a) ? 1 : 0, cb = inCopyDir(b) ? 1 : 0;
      if (ca !== cb) return ca - cb;
      return a.length - b.length;
    });
    keeperPerSha.set(h, ordinati[0]);
  }

  const proposti = [];
  for (const f of ctx.file) {
    const prova = dimostra(f, ctx, keeperPerSha);
    // The filter is on `prova.prova`, NOT on the object. Returning an object whose
    // `prova` is null still returns a truthy object, and the first real run
    // cheerfully listed 4 219 files with `[null]` next to them — a plan that says
    // "propose everything, and here is no reason". *A guard on the wrong field is a
    // guard that is not there.*
    if (prova && prova.prova) proposti.push({ ...f, prova: prova.prova, perche: prova.perche });
  }
  proposti.sort((a, b) => b.bytes - a.bytes);

  const byteTrovati = ctx.file.reduce((s, f) => s + f.bytes, 0);
  const byteProposti = proposti.reduce((s, f) => s + f.bytes, 0);
  return {
    generatoIl: new Date().toISOString(),
    radici: roots,
    contatori: {
      fileTrovati: ctx.file.length,
      fileProtetti: ctx.protetti.length,
      fileProposti: proposti.length,
      byteTrovati,
      byteProposti,
      byteCancellati: 0
    },
    proposte: proposti,
    // The protected list goes in the manifest too: the next reader must be able
    // to see WHAT WAS SPARED, not only what was offered. A manifest that lists
    // only the victims is a manifest that cannot be argued with.
    protetti: ctx.protetti.map((p) => ({ path: p.path, perche: p.perche })),
    regola: 'UN FILE CHE ESISTE IN UN POSTO SOLO NON È UN RESIDUO: È L\'UNICA COPIA.'
  };
}

function percheProtetto(p, ctx) {
  const nome = basename(p);
  // EVERY pattern above is written with forward slashes, and on this machine the
  // paths arrive with backslashes. The first real run proved what that costs: the
  // `.done` rule silently never matched, 500-odd archived messages were walked and
  // hashed as if they were candidates, and the only reason nothing was deleted was
  // that a second, unrelated bug happened to stop it. *A protection list that does
  // not match the paths it is given is not a protection list, it is a comment.*
  const norm = p.replace(/\\/g, '/');
  if (MAI_PER_NOME.has(nome)) return 'memoria del pavimento: ' + nome;
  if (MAI_PER_SUFFISSO.some((s) => nome.endsWith(s))) return 'lavoro non committato: ' + nome;
  for (const t of MAI_PER_TASTO) if (t.per.test(norm)) return t.perche;
  if (norm.includes('/resources/skills/pulizia_residui_lavorazione/')) {
    return 'la skill non e\' un proprio residuo: se si include, la prossima esecuzione cerca di cancellare se\' stessa';
  }
  if (ctx.dichiarati.has(nome)) return 'una card aperta lo dichiara';
  if (ctx.carteOk === false) return ctx.motivoLedger;
  return null;
}

/** Exactly one of the three proofs, or nothing. */
function dimostra(f, ctx, keeperPerSha) {
  // GEMELLO — the same content exists elsewhere, at least one copy is in a copy
  // directory, AND this file is not the one the set keeps. A pure fact about
  // bytes, and the only proof that needs no opinion at all.
  if (f.sha) {
    const gemelli = (ctx.hashPerSha.get(f.sha) || []).filter((q) => q !== f.path);
    if (gemelli.length) {
      if (!inCopyDir(f.path) && !gemelli.some(inCopyDir)) {
        return { prova: null, perche: 'contenuto identico ma NESSUNA delle due copie e\' in una directory di copia: due file con lo stesso testo non sono una copia, e trattarli come tale cancella un originale' };
      }
      const keeper = keeperPerSha.get(f.sha);
      if (keeper === f.path) {
        return { prova: null, perche: 'e\' LA COPIA CHE IL GRUPPO TENNE: ' + gemelli.length + ' file identici esistono, e questo e\' quello che resta se gli altri se ne vanno. Un set senza un custode e\' un set che sparisce' };
      }
      return {
        prova: 'gemello',
        perche: 'contenuto identico (sha ' + f.sha.slice(0, 12) + '…) in ' + gemelli.length
          + ' altro/i file, almeno uno in una directory di copia; resta ' + relative(ROOTS[0], keeper)
      };
    }
  }
  // FUORI USO — this was my first implementation and it was a TRAP, and the trap
  // is worth writing down because it is easy to fall into again.
  //
  // Read literally, "no open card declares it, no tool reads it, no config names
  // it" is true of almost EVERY file in a repository — including the source code.
  // The first real dry run proved it: it proposed 4 218 files out of 4 218
  // found, among them `docs/media/hero.mp4` and a skill's illustrations, all
  // labelled «fuori uso». *Absence of a reference is not derivation: it is the
  // normal state of every file, and a proof that is true of everything proves
  // nothing.*
  //
  // So `fuori uso` does NOT authorise a deletion. It is recorded as a NOTE, next
  // to the file, and the file is not proposed. The only two things that authorise
  // are the two the card's governing rule actually names: the same content exists
  // elsewhere, or a command that still rebuilds it. *The card lists three proofs
  // and then says only derived files may be deleted; those two sentences do not
  // agree, and the one that says «derivato» wins, because the other one would
  // delete the repository.*
  const nota = fuoriUso(f.path, ctx);
  return { prova: null, perche: 'fuori uso NON prova niente: ' + nota.perche };
}

function percorsoManifesto() {
  const d = join(HIVE, 'pulizia');
  mkdirSync(d, { recursive: true });
  const giorno = new Date().toISOString().slice(0, 10);
  return join(d, `pulizia-${giorno}.json`);
}

function stampa(piano, cancellati) {
  const c = piano.contatori;
  console.log('pulizia_residui_lavorazione — ' + new Date().toISOString());
  console.log('  file trovati   : ' + c.fileTrovati);
  console.log('  file protetti  : ' + c.fileProtetti);
  console.log('  file proposti  : ' + c.fileProposti);
  console.log('  byte trovati   : ' + c.byteTrovati);
  console.log('  byte proposti  : ' + c.byteProposti);
  console.log('  byte cancellati: ' + (cancellati === undefined ? 0 : cancellati));
  if (piano.proposte.length) {
    console.log('\n  proposte (percorso | byte | prova | perche):');
    for (const p of piano.proposte.slice(0, 40)) {
      console.log('    ' + p.path);
      console.log('        ' + p.bytes + ' B  [' + p.prova + ']  ' + p.perche);
    }
    if (piano.proposte.length > 40) console.log('    ... e altre ' + (piano.proposte.length - 40));
  }
  console.log('\n  regola: ' + piano.regola);
}

// ── main ────────────────────────────────────────────────────────────────────
function main(argv) {
  const applica = argv.includes('--applica');
  const iMan = argv.indexOf('--manifest');
  const piano = costruisciPiano({});

  if (!applica) {
    const p = percorsoManifesto();
    writeFileSync(p, JSON.stringify(piano, null, 2), 'utf8');
    stampa(piano);
    console.log('\n  manifesto: ' + p);
    console.log('  NESSUN FILE CANCELLATO. La seconda esecuzione la preme l\'umano, guardando questo elenco.');
    return 0;
  }

  // ── --applica: the manifest decides, and only the manifest ──
  const da = iMan >= 0 ? argv[iMan + 1] : percorsoManifesto();
  if (!da || !existsSync(da)) {
    console.error('NON CANCELLO NIENTE: nessun manifesto in "' + (da || '(manca --manifest)') + '".');
    console.error('  --applica cancella solo ciò che una --dry-run ha già scritto e che l\'umano ha guardato.');
    return 3;
  }
  let m;
  try { m = JSON.parse(readFileSync(da, 'utf8')); } catch {
    console.error('NON CANCELLO NIENTE: il manifesto non è JSON leggibile (' + da + ').');
    return 4;
  }
  const eta = (Date.now() - Date.parse(m.generatoIl)) / 86400000;
  if (!(eta <= MAX_AGE_GIORNI)) {
    console.error('NON CANCELLO NIENTE: il manifesto ha ' + eta.toFixed(1) + ' giorni, e il massimo è ' + MAX_AGE_GIORNI + '.');
    console.error('  Un piano vecchio descrive un disco che nel frattempo è cambiato: rifai la --dry-run.');
    return 5;
  }
  if (!Array.isArray(m.proposte) || !m.proposte.length) {
    console.error('NON CANCELLO NIENTE: il manifesto non propone nulla. E\' il caso normale su un pavimento pulito.');
    return 0;
  }

  let cancellati = 0, saltati = 0, byteCancellati = 0;
  const registro = [];
  for (const p of m.proposte) {
    // Re-verify BOTH that it is still what the manifest said, and that it is still
    // protected-free. A path can have become something else between the plan and
    // the press, and that is the window where work is lost.
    let st; try { st = statSync(p.path); } catch { saltati++; registro.push({ path: p.path, esito: 'non esiste piu\'' }); continue; }
    const h = sha256(p.path);
    if (p.sha && h !== p.sha) { saltati++; registro.push({ path: p.path, esito: 'contenuto cambiato: non e\' piu\' quello approvato' }); continue; }
    if (percheProtetto(p.path, { dichiarati: new Set() })) { saltati++; registro.push({ path: p.path, esito: 'ora e\' protetto' }); continue; }
    try { unlinkSync(p.path); cancellati++; byteCancellati += st.size; registro.push({ path: p.path, esito: 'cancellato', bytes: st.size }); }
    catch (e) { saltati++; registro.push({ path: p.path, esito: 'cancellamento fallito: ' + e.code }); }
  }
  m.contatori.byteCancellati = byteCancellati;
  m.esito = { cancellati, saltati, byteCancellati, eseguitoIl: new Date().toISOString() };
  writeFileSync(da, JSON.stringify(m, null, 2), 'utf8');
  stampa(m, byteCancellati);
  console.log('\n  cancellati: ' + cancellati + '  saltati: ' + saltati);
  for (const r of registro.slice(0, 40)) console.log('    ' + r.esito + '  ' + r.path);
  if (saltati) console.log('\n  I SALTATI NON SONO UN ERRORE: sono file che nel frattempo non erano piu\' quelli approvati,');
  console.log('  e cancellarli avrebbe significato cancellare qualcosa di diverso da cio che e\' stato approvato.');
  return 0;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  process.exit(main(process.argv.slice(2)));
}
